version: '3.9'

services:
  app:
    image: kammeph/progress
    container_name: progress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      API_URL: ${API_URL}
    ports:
      - 4080:80
      - 4443:443
    restart: always
