version: "3.9"

services:
  app:
    image: kammeph/progress
    container_name: progress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      API_URL: ${API_URL}
    ports:
      - 8088:80
      - 3443:443
